### ISSUE TITLE
No explanation as to why an index fails to generate

### ISSUE THREAD

**Issue by JudoWill** [Cibiv/Teaser#6]
Trying to run a test using the provided e-coli dataset I get an error message that the index failed to generate but I can't seem to find the source of the error. Can you point me in the direction of how Teaser generates the index so I can debug the problem?

Log-file appended below.

> [11:27:09] [Main        ] framework cmd:  ./teaser.py setups_generated/0fb49191948262cce8b48bc5cbce2cd9.yaml
> [11:27:09] [Main        ] framework hash: vevev
> [11:27:09] [Main        ] deployment mode: production (False)
> [11:27:09] [Main        ] Test Runner Setup - ""
> [11:27:09] [Main        ] Using Teaser for data set creation
> [11:27:09] [Teaser      ] Init. Creating 1 test datasets.
> [11:27:09] [Teaser      ] 
> [11:27:09] [Teaser      ] Creating test 0fb49191948262cce8b48bc5cbce2cd9
> [11:27:09] [Teaser      ] change directory /data/Teaser/tests_generated/0fb49191948262cce8b48bc5cbce2cd9
> [11:27:09] [Teaser      ] change directory /data/Teaser/tests_generated/0fb49191948262cce8b48bc5cbce2cd9
> [11:27:09] [Teaser      ] Indexing /data/Teaser/references/E_coli.fasta
> [11:27:09] [Teaser      ] Teaser: Test creation failed for '0fb49191948262cce8b48bc5cbce2cd9' due to an exception: Indexing failed
> [11:27:09] [Teaser      ] Teaser Error, exception: Traceback (most recent call last):
>   File "/data/Teaser/lib/teaser.py", line 134, in createTest
>     self.makeDatasetDS(test)
>   File "/data/Teaser/lib/teaser.py", line 238, in makeDatasetDS
>     idx = gsample.index(test["reference"], self.config["fastindex_path"])
>   File "/data/Teaser/lib/gsample.py", line 26, in index
>     raise Exception("Indexing failed")
> Exception: Indexing failed
> [11:27:09] [ReportGen   ] This benchmark contains no tests. This could be because no tests or mappers were selected, or because generation/loading failed for all tests.

**Comment by JudoWill** [comment]
Although running through the `teaser.py setups_generated/-hash-.yaml` runs through completion.  Puzzling.

**Comment by smolkmo** [comment]
Thank you very much for your interest & taking the time to report this Will!

The error indicates that the call to `tools/fastindex <reference.fasta>` failed, which based on your description is highly likely due to the binary not being accessible from the main script. This points to a path-related issue we have not seen before. If you did not already, I suggest trying to start `server.py` while being inside the teaser root directory. It is also worth trying to start it using `python server.py`, while making sure that the `python` command refers to a 2.x version of Python.

If the problem does persist, using the web interface to create + the `./teaser.py setups_generated/-hash-.yaml` command to run your benchmarks is the best short-term fix, which you already discovered yourself.

If possible, knowing your OS + Python versions would be very helpful for us in trying to reproduce this.

**Comment by JudoWill** [comment]
Yes, ended up being a path Issue. I added the `lib` directory to the python path and everything worked out fine.
