### ISSUE TITLE
Installation failure on MacOS

### ISSUE THREAD

**Issue by mshadbolt** [Cibiv/Teaser#8]
Hi, your tool looks really great, I tried installing because I have a different organsim reference I'd like to try out but I get the following error when it gets to the point of building DWGSIM:

```
Building DWGSIM...
make[2]: Nothing to be done for `lib'.
make[2]: Nothing to be done for `lib'.
make[2]: Nothing to be done for `lib'.
gcc -g -Wall -O3  -o samtools bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o  libbam.a -Lbcftools -lbcf   -lm -lz -lpthread
ld: warning: ignoring file bcftools/libbcf.a, file was built for archive which is not the architecture being linked (x86_64): bcftools/libbcf.a
Undefined symbols for architecture x86_64:
  "_bcf_close", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_destroy", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_hdr_destroy", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_hdr_sync", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_hdr_write", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_open", referenced from:
      _mpileup in bam_plcmd.o
  "_bcf_str2id", referenced from:
      _mplp_func in bam_plcmd.o
  "_bcf_str2id_add", referenced from:
      _bam_mpileup in bam_plcmd.o
  "_bcf_str2id_init", referenced from:
      _bam_mpileup in bam_plcmd.o
  "_bcf_str2id_thorough_destroy", referenced from:
      _bam_mpileup in bam_plcmd.o
  "_bcf_sync", referenced from:
      _bcf_call2bcf in bam2bcf.o
  "_bcf_write", referenced from:
      _mpileup in bam_plcmd.o
  "_kt_fisher_exact", referenced from:
      _bcf_call2bcf in bam2bcf.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [samtools] Error 1
make: *** [all-recur] Error 1
Building tools...
Errors occured during installation:
    Command failed: make
```

I am trying to install on a MacBook Pro OSX El Capitan. Let me know if you need any further info to try and debug. I think the issue is with the samtools installation, found this thread from a few years ago though no solution... (https://sourceforge.net/p/samtools/mailman/message/31317877/)
I have installed and updated Command line tools, gcc version below.

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

Has anyone else encountered issues installing attempting to install mac or have any work around for me?

**Comment by smolkmo** [comment]
Hi Marion,

Thanks for your interest in Teaser!

Noting from the log you posted, the installation seems to really only run into trouble for dwgsim. Teaser uses the Mason simulator by default, except for Ion Torrent reads, so as long as you do not need to simulate this type of read - all things should run fine.

For benchmarking Bowtie2 on Mac, I advise downloading the newest OSX binaries directly from https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.2.9/bowtie2-2.2.9-macos-x86_64.zip/download . You would then just have to replace the folder teaser/software/bowtie2, and extract the above archive in a way so that the newly downloaded bowtie2 binaries can be accessed by teaser under teaser/software/bowtie2/bowtie2, teaser/software/bowtie2/bowtie2-build, teaser/software/bowtie2/bowtie2-align, etc.

If you continue to experience problems trying to run Teaser on OSX, you could also consider using the Teaser VM machine image, where everything is already set up. You can download it at http://www.cibiv.at/software/teaser/Teaser_current.ova

Hope this helped!
Moritz

**Comment by mshadbolt** [comment]
Hi Moritz, 
Thanks for the speedy reply, I'll give it a go, only interested in Illumina reads so no need for dwgsim. Will let you know if I have any further issues.

Also you might want to update the link to the VM in your Readme.md, the link there currently gives a 404, whereas the one above works perfectly.

Thanks
Marion
